echo "===== SYSTEM INFORMATION ====="
echo "User        : $(who)"
echo "Hostname    : $(hostname)"
echo "OS          : $(uname -s)"
echo "Kernel      : $(uname -r)"
echo "Architecture: $(uname -m)"
echo "Current Dir : $(pwd)"
echo "Shell       : $($SHELL)"
echo "Date        : $(date)"
echo "Time        : $(date)"